inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

  Exclude:
    - db/schema.rb
    - db/seeds.rb
    - bin/bundle

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb